services:
  - type: web
    name: fairgig-node-backend
    runtime: node
    rootDir: node-backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: FRONTEND_URL_PRODUCTION
        sync: false
