services:
  - type: web
    name: fairgig-node-backend
    runtime: node
    rootDir: node-backend
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: FRONTEND_URL_PRODUCTION
        sync: false
  - type: web
    name: fairgig-earnings-fastapi
    runtime: python
    rootDir: earnings-service-fastApi
    plan: free
    buildCommand: pip install playwright && pip install -r requirements.txt && playwright install chromium
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL_PRODUCTION
        sync: false
  - type: web
    name: fairgig-anomaly-service
    runtime: python
    rootDir: anomaly-service
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB_NAME
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL_PRODUCTION
        sync: false
